/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_paomian_app2_util_NativeCaculator */

#ifndef _Included_com_paomian_app2_util_NativeCaculator
#define _Included_com_paomian_app2_util_NativeCaculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_paomian_app2_util_NativeCaculator
 * Method:    add
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_paomian_app2_util_NativeCaculator_add
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
